#!/usr/bin/env python3
"""
Load embeddings from Parquet into Qdrant (local).

Assumes embeddings generated by hf_vectorizer.vectorizer.
"""

import logging
import sys
from pathlib import Path
from tqdm import tqdm

import numpy as np
import pyarrow.parquet as pq

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct


from hf_vectorizer.config import (
    DEFAULT_EMBEDDINGS_FILE,
    QDRANT_URL,
    QDRANT_COLLECTION_NAME,
)


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def load_parquet_to_qdrant(
    parquet_path: Path = DEFAULT_EMBEDDINGS_FILE,
    qdrant_url: str = QDRANT_URL,
    collection_name: str = QDRANT_COLLECTION_NAME,
    batch_size: int = 256,
):
    # ---- validation ----
    if not parquet_path.exists():
        raise FileNotFoundError(f"Parquet file not found: {parquet_path}")

    logger.info(f"Loading parquet file: {parquet_path}")

    pf = pq.ParquetFile(parquet_path)

    # ---- infer vector dimension ----
    first_batch = next(pf.iter_batches(batch_size=1))
    first_df = first_batch.to_pandas()

    if "vector" not in first_df.columns:
        raise ValueError("Parquet must contain 'vector' column")

    sample_vec = np.asarray(first_df["vector"].iloc[0], dtype=np.float32)
    vector_dim = sample_vec.shape[0]

    logger.info(f"Detected vector dimension: {vector_dim}")

    # ---- connect to Qdrant ----
    logger.info(f"Connecting to Qdrant at {qdrant_url}")
    client = QdrantClient(url=qdrant_url)

    # ---- create collection ----
    try:
        client.get_collection(collection_name)
        logger.info(f"Collection '{collection_name}' already exists")
    except Exception:
        logger.info(f"Creating collection '{collection_name}'")
        client.create_collection(
            collection_name=collection_name,
            vectors_config=VectorParams(
                size=vector_dim,
                distance=Distance.COSINE,
            ),
        )

    # ---- upload ----
    logger.info("Starting upload...")
    global_idx = 0

    for batch in tqdm(pf.iter_batches(batch_size=batch_size), desc="Uploading"):
        df = batch.to_pandas()

        # Stack vectors directly as float32
        vectors = np.vstack(df["vector"].values).astype(np.float32, copy=False)

        points = []

        for i, (vector, row) in enumerate(zip(vectors, df.itertuples(index=False))):
            payload = {}

            for col in df.columns:
                if col == "vector":
                    continue

                val = getattr(row, col, None)

                if isinstance(val, np.integer):
                    payload[col] = int(val)
                elif isinstance(val, np.floating):
                    payload[col] = float(val)
                elif isinstance(val, np.ndarray):
                    payload[col] = val.tolist()
                elif isinstance(val, (list, tuple)):
                    payload[col] = list(val)
                else:
                    payload[col] = val

            points.append(
                PointStruct(
                    id=global_idx,
                    vector=vector.tolist(),
                    payload=payload,
                )
            )

            global_idx += 1

        client.upsert(
            collection_name=collection_name,
            points=points,
        )

    logger.info("Upload complete")

    info = client.get_collection(collection_name)
    logger.info(f"Total points: {info.points_count}")
    logger.info(f"Vector size: {info.config.params.vectors.size}")


def main():
    parquet_path = DEFAULT_EMBEDDINGS_FILE

    if len(sys.argv) > 1:
        parquet_path = Path(sys.argv[1])

    qdrant_url = sys.argv[2] if len(sys.argv) > 2 else QDRANT_URL
    collection_name = sys.argv[3] if len(sys.argv) > 3 else QDRANT_COLLECTION_NAME

    try:
        load_parquet_to_qdrant(
            parquet_path=parquet_path,
            qdrant_url=qdrant_url,
            collection_name=collection_name,
        )
    except Exception as e:
        logger.error(f"Error: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()